import './assets/scss/template.scss'
import './assets/images/desk.jpg'
import './assets/images/CBS_logo.svg'
import './assets/images/slash-logo.png'
import './assets/images/Logo-Lenovo.png'
import './assets/images/Button-Black-Large.png'
import './assets/images/FBTMinimalBlack.png'
import './assets/images/sensus-xylem.png'
import './assets/images/transcirrus.jpg'
import './assets/images/In-Black-128px-TM.png'
import './assets/images/GitHub-Mark-120px-plus.png'
import './assets/images/dr-mcgill.png'
import './assets/images/super-pretendo-transparent.png'
import './assets/images/chelsea-cullen-logo.png'
import './assets/images/whale.png'
import './assets/images/frg-logo.png'

import 'popper.js'
import 'bootstrap'
import AOS from 'aos'
import './assets/js/jquery.singlePageNav'
import './assets/js/custom'

AOS.init()
